baseURL = 'https://rubydev.org/'
languageCode = 'en-us'
title = 'RubyDev'
theme = 'DoIt'

[params.page.code]
    # the maximum number of lines of displayed code by default
    maxShownLines = 10000
    # whether to enable line numbers in the code block
    lineNos = true
    # whether to enable line wrapping in the code block
    wrap = false
    # whether to display the header in the code block
    header = true